Repository kubernetes-csi/kubernetes-csi-migration-library, pull requests merged in 2018-10, with the labels that each got.

#3 Updated apimachinerydep
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, size/XS

#4 Add tranlation plugin for AWS EBS
  .gitignore
  plugins/aws_ebs.go
  plugins/gce_pd.go
  plugins/in_tree_volume.go
  translate.go
  translate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6 Add GetCSINameFromIntreeName function for node label migration
  translate.go
Labels: approved

#7 Add fix for when zone label empty
  plugins/gce_pd.go
Labels: approved, cncf-cla: yes
